# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField()),
                ('body', models.TextField()),
                ('signature', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
