# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamper', '0002_auto_20170619_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
